---
title: "p8105_hw6_yj2688"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(p8105.datasets)
library(readxl)
library(patchwork)
library(ggplot2)
library(viridis)
library(modelr)
library(mgcv)
library(leaps)
set.seed(1)

```


## Problem 1

```{r, warning=FALSE, message=FALSE}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

bootstrap = weather_df %>% 
  bootstrap(n = 5000, id = "strap_n") %>% 
  mutate(strap = map(strap, as_tibble), 
         models = map(strap, ~lm(tmax ~ tmin, data = .x)),
         estimates = map(models, broom::tidy),
         summary = map(models, broom::glance)) %>% 
  select(-strap, -models) %>% 
  unnest(c(estimates, summary), names_repair = "universal") 

bootstrap = bootstrap %>%
  select(strap_n, term, estimate, r.squared) %>% 
  pivot_wider(id_cols = c(strap_n, r.squared),
              names_from = term,
              values_from = estimate) %>% 
  rename(beta0 = `(Intercept)`,
         beta1 = "tmin") %>% 
  mutate(logb0_b1 = log(beta0 * beta1)) %>% 
  select(-beta0, -beta1)

```

```{r, warning=FALSE, message=FALSE}

r2 = bootstrap %>% 
  select(r.squared) %>% 
  summarize(lowwerbound = quantile(r.squared, 0.025), upperbound = quantile(r.squared, 0.975))

r2 %>%
  knitr::kable(digits = 3)

log = bootstrap %>% 
  select(logb0_b1) %>% 
  summarize(lowwerboundi = quantile(logb0_b1, 0.025), upperbound = quantile(logb0_b1, 0.975))

log %>%
  knitr::kable(digits = 3)

bootstrap %>% 
  select(r.squared) %>% 
  ggplot(aes(x = r.squared)) + 
  geom_density() + 
  labs(x = "Estimated R^2",
       y = "Density",
    title = "Estimated R^2 Distribution (bootstrap 5000)")

bootstrap %>% 
  select(logb0_b1) %>% 
  ggplot(aes(x = logb0_b1)) + 
  geom_density() + 
  labs(x = "Estimated log(beta0*beta1)",
       y = "Density",
    title = "Estimated log(beta0*beta1) Distribution (bootstrap 5000)")


```
Both the R^2 and log(beta0*beta1) seems to be normally distributed on the graph. 

## Problem 2

```{r, warning=FALSE, message=FALSE}
#Importing the homicide file into R
csvurl <- 'https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv'
rawhomicide <- read_csv(url(csvurl), show_col_types = FALSE)

homicide <- rawhomicide %>% 
  mutate(city_state = str_c(city,", ",state),
         status = as.numeric(disposition == "Closed by arrest")) %>% 
  filter(!city_state %in% c('Dallas, TX','Phoenix, AZ','Kansas City, MO','Tulsa, AL')) %>%
  mutate(victim_race = fct_relevel(ifelse(victim_race == "White", "white", "non-white"), "white")) %>%
  mutate_at(c('victim_age'), as.numeric)

```


```{r, warning=FALSE, message=FALSE}
#use the glm function to fit a logistic regression for Baltimore with resolved vs unresolved as the outcome and victim age, sex and race as predictors
baltimore = homicide %>%
   filter(city_state %in% c('Baltimore, MD'))

fit_logistic = 
  baltimore %>% 
  glm(status ~ victim_age + victim_race + victim_sex, data = ., family = binomial()) 

fit_logistic %>% 
  broom::tidy() %>% 
  mutate(OR = exp(estimate)) %>%
  mutate(low_CI = exp(estimate - std.error * 1.96)) %>% 
  mutate(high_CI = exp(estimate + std.error * 1.96)) %>%
  select(term, log_OR = estimate, OR, p.value, low_CI, high_CI) %>% 
  knitr::kable(digits = 3)

save(fit_logistic, file = "./baltimore_glm.RData")
```

The odds ratio of murder in male is 0.412 times lower than female, 95% CI: [0.315, 0.537]. 


```{r, warning=FALSE, message=FALSE}
#use the glm function to every city
homicide_nest = homicide %>% 
  group_by(city_state) %>% 
  nest() %>% 
    mutate(logit = map(data, ~glm(status ~ victim_sex + victim_race + victim_age, 
                                      family = binomial, data = .x)), 
         logit = map(logit, broom::tidy)) %>% 
  select(-data) %>% 
  unnest() 

model = homicide_nest %>% 
  mutate(OR = exp(estimate), 
         low_CI = exp(estimate - 1.96*std.error), 
         high_CI = exp(estimate + 1.96*std.error)) %>% 
  filter(term == "victim_sexMale") %>% 
  select(OR, low_CI, high_CI)

model %>% knitr::kable(digits = 3)

model %>% 
  ggplot(aes(x = city_state, y = OR)) + 
  geom_point(alpha = 0.50) +
  geom_errorbar(mapping = aes(ymin = low_CI, ymax = high_CI)) +
  theme_bw() +
  theme(legend.position = "none",
        legend.direction = "horizontal",
         legend.key.size = unit(0.04, "cm"))+
  coord_flip() + 
      labs(title = "Homicide Odds Ratio of sex by City", 
        x = "City State",
        y = "Sex Odds Ratio") 

```

